# -*- coding: utf-8 -*-
"""Tests for the public plugin registration contract."""

import json
from pathlib import Path
from unittest.mock import Mock

from plugins.memory.openviking.backend.manager import OpenVikingMemoryManager
from plugins.memory.openviking.plugin import OpenVikingMemoryPlugin


def test_plugin_registers_memory_backend_and_network_tool_governance():
    api = Mock()

    OpenVikingMemoryPlugin().register(api)

    kwargs = api.register_memory_backend.call_args.kwargs
    assert kwargs["backend_id"] == "openviking"
    assert kwargs["factory"] is OpenVikingMemoryManager
    assert kwargs["metadata"]["secret_fields"] == ["api_key"]
    assert kwargs["metadata"]["tools"]["memory_search"] == {
        "policy_name": "OpenVikingMemorySearch",
        "tool_type": "network",
        "target_param": "query",
    }


def test_manifest_matches_plugin_registration_and_frontend_entry():
    root = Path(__file__).parents[1]
    manifest = json.loads((root / "plugin.json").read_text(encoding="utf-8"))

    assert manifest["id"] == "memory-openviking"
    assert manifest["type"] == "memory"
    assert manifest["meta"]["memory_backends"] == [
        {"id": "openviking", "label": "OpenViking"},
    ]
    # The distributable bundle is intentionally generated by ``npm run build``
    # and ignored by Git, matching the other in-tree memory plugins.
    assert manifest["entry"]["frontend"] == "frontend/dist/index.js"
